version: '3'
services:
  backup-postgres-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./backups:/app/backups
    deploy:
      restart_policy:
        condition: on-failure
